### ISSUE TITLE
New files in /etc are discarded after any operation

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/ABRoot#247]
For example, locales in /etc/locales are discarded after each upgrade. 

This is cased by a bug in EtcBuilder.

**Comment by axtloss** [comment]
Fixed in [EtcBuilder release 1.1](https://github.com/linux-immutability-tools/EtcBuilder/releases/tag/v1.1)
There are no changes that affect the way EtcBuilder is used so a simple version bump should be enough.

**Comment by taukakao** [comment]
Not sure if I'm doing something wrong here but I made a build with the new version https://github.com/taukakao/ABRoot/actions/runs/8669365790 but when I use this version of abroot, it behaves exactly like before.

**Comment by taukakao** [comment]
I can now confirm that https://github.com/linux-immutability-tools/EtcBuilder/issues/1 still persists

**Comment by taukakao** [comment]
There's another bug, since #251 doesn't fix the problem.
I'm investigating.
